management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200, http://localhost:9000

logging:
  level:
    web: debug
    org.springframework.security: debug

security:
  enable-csrf: false

# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true