# Documents for apllication properties
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#core-properties

server:
  servlet:
    context-path: /api
  port: 9000

spring:
  profiles:
    active: dev
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false