management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200, http://localhost:9000

logging:
  level:
    web: debug
    org.springframework.security: info

security:
  enable-csrf: false

# Enabling H2 Console
spring:
  datasource:
    initialization-mode: always
    platform: h2
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true